/** 
 * This file was automatically generated by the procedure 
 * 'build_boot_image' in 'base-hw/run/env'. 
 */ 
 
.section .data 
 
.p2align 2 
.global _boot_modules_begin 
_boot_modules_begin: 
.string "GROM" 
 
.p2align 2 
.global _boot_module_headers_begin 
_boot_module_headers_begin:

.long mod1_name 
.long mod1_start 
.long mod1_end - mod1_start

.long mod2_name 
.long mod2_start 
.long mod2_end - mod2_start

.long mod3_name 
.long mod3_start 
.long mod3_end - mod3_start

.long mod4_name 
.long mod4_start 
.long mod4_end - mod4_start

.long mod5_name 
.long mod5_start 
.long mod5_end - mod5_start

.global _boot_module_headers_end 
_boot_module_headers_end: 

.p2align 2 
mod1_name: 
.string "init" 
.byte 0 

.p2align 2 
mod2_name: 
.string "vmm" 
.byte 0 

.p2align 2 
mod3_name: 
.string "linux" 
.byte 0 

.p2align 2 
mod4_name: 
.string "initrd.gz" 
.byte 0 

.p2align 2 
mod5_name: 
.string "config" 
.byte 0 

.p2align 12 
mod1_start: 
.incbin "var/run/vmm/genode/init" 
mod1_end: 

.p2align 12 
mod2_start: 
.incbin "var/run/vmm/genode/vmm" 
mod2_end: 

.p2align 12 
mod3_start: 
.incbin "var/run/vmm/genode/linux" 
mod3_end: 

.p2align 12 
mod4_start: 
.incbin "var/run/vmm/genode/initrd.gz" 
mod4_end: 

.p2align 12 
mod5_start: 
.incbin "var/run/vmm/genode/config" 
mod5_end: 

.global _boot_modules_end 
_boot_modules_end:
